/* The following code was generated by JFlex 1.6.1 */

package compilador;
import java_cup.runtime.Symbol;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.ComplexSymbol;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>C:/Users/Esteban/Desktop/Universidad/compilador_repo/Compilador/src/compilador/Lexico.flex</tt>
 */
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\27\1\31\1\0\1\27\1\31\22\0\1\27\1\3\1\30"+
    "\1\0\1\34\1\4\1\1\1\0\1\14\1\15\1\12\1\10\1\22"+
    "\1\11\1\32\1\13\12\26\1\24\1\23\1\7\1\6\1\5\2\0"+
    "\1\63\1\25\1\61\1\60\1\46\1\50\1\71\1\43\1\44\2\25"+
    "\1\45\1\72\1\66\1\70\1\67\1\25\1\64\1\52\1\102\1\101"+
    "\1\62\1\42\3\25\1\20\1\0\1\21\1\0\1\33\1\0\1\56"+
    "\1\25\1\54\1\53\1\41\1\47\1\75\1\36\1\37\2\25\1\40"+
    "\1\76\1\65\1\74\1\73\1\25\1\57\1\51\1\100\1\77\1\55"+
    "\1\35\3\25\1\16\1\2\1\17\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uff92\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\3"+
    "\23\1\1\26\1\27\1\30\1\31\1\32\1\33\1\0"+
    "\1\34\1\0\1\35\1\36\1\0\1\37\25\0\1\40"+
    "\1\0\1\41\2\0\1\41\11\0\1\42\2\0\1\43"+
    "\10\0\1\44\3\0\1\45\2\0\1\46\10\0\1\47"+
    "\1\50\4\0\1\51\1\0\1\52";

  private static int [] zzUnpackAction() {
    int [] result = new int[129];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\103\0\103\0\206\0\311\0\103\0\u010c\0\u014f"+
    "\0\u0192\0\103\0\103\0\103\0\u01d5\0\103\0\103\0\103"+
    "\0\103\0\103\0\103\0\103\0\103\0\103\0\u0218\0\103"+
    "\0\u025b\0\u029e\0\u02e1\0\u0324\0\u0367\0\u03aa\0\u03ed\0\u0430"+
    "\0\u0473\0\u04b6\0\u04f9\0\u053c\0\u057f\0\u05c2\0\u0605\0\u0648"+
    "\0\u068b\0\u06ce\0\u0711\0\103\0\103\0\103\0\103\0\103"+
    "\0\103\0\u0754\0\u029e\0\u025b\0\103\0\u0797\0\u07da\0\103"+
    "\0\u081d\0\u0860\0\u08a3\0\u08e6\0\u0929\0\u096c\0\u09af\0\u09f2"+
    "\0\u0a35\0\u0a78\0\u0abb\0\u0afe\0\u0b41\0\u0b84\0\u0bc7\0\u0c0a"+
    "\0\u0c4d\0\u0c90\0\u0cd3\0\u0d16\0\u0d59\0\103\0\u0d9c\0\u0ddf"+
    "\0\u0e22\0\u0e65\0\u0ea8\0\u0eeb\0\u0f2e\0\u0f71\0\u0fb4\0\u0ff7"+
    "\0\u103a\0\u107d\0\u10c0\0\u1103\0\103\0\u1146\0\u1189\0\103"+
    "\0\u11cc\0\u120f\0\u1252\0\u1295\0\u12d8\0\u131b\0\u135e\0\u13a1"+
    "\0\103\0\u13e4\0\u1427\0\u146a\0\103\0\u14ad\0\u14f0\0\103"+
    "\0\u1533\0\u1576\0\u15b9\0\u15fc\0\u163f\0\u1682\0\u16c5\0\u1708"+
    "\0\103\0\103\0\u174b\0\u178e\0\u17d1\0\u1814\0\103\0\u1857"+
    "\0\103";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[129];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\2\1\27\1\30"+
    "\1\31\1\30\1\32\1\33\1\2\1\34\1\2\1\35"+
    "\1\2\1\36\1\37\1\2\1\40\1\2\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\3\2\1\50\1\51"+
    "\5\2\1\52\3\2\1\53\7\2\105\0\1\54\103\0"+
    "\1\55\105\0\1\56\102\0\1\57\101\0\1\60\1\61"+
    "\130\0\1\62\74\0\1\27\3\0\1\63\50\0\30\64"+
    "\1\65\1\0\51\64\26\0\1\63\101\0\1\66\7\0"+
    "\46\66\36\0\1\67\113\0\1\70\15\0\1\71\55\0"+
    "\1\72\24\0\1\73\60\0\1\74\106\0\2\70\15\0"+
    "\1\75\61\0\1\76\20\0\1\77\54\0\1\100\107\0"+
    "\1\101\135\0\1\102\104\0\1\103\41\0\1\104\117\0"+
    "\1\105\72\0\1\106\117\0\1\107\103\0\1\110\14\0"+
    "\1\111\60\0\1\112\17\0\1\113\3\0\34\62\1\114"+
    "\46\62\25\0\2\66\6\0\46\66\37\0\1\115\143\0"+
    "\1\116\53\0\1\117\104\0\1\120\73\0\1\121\140\0"+
    "\1\116\52\0\1\122\110\0\1\123\116\0\1\124\76\0"+
    "\1\125\71\0\1\126\107\0\1\127\72\0\1\130\113\0"+
    "\1\131\76\0\1\132\107\0\1\133\104\0\1\134\114\0"+
    "\1\135\74\0\1\136\106\0\1\135\2\0\13\62\1\30"+
    "\20\62\1\114\46\62\40\0\1\137\103\0\1\140\114\0"+
    "\1\141\74\0\1\142\103\0\1\140\102\0\1\143\112\0"+
    "\1\144\107\0\1\145\56\0\1\146\107\0\1\147\113\0"+
    "\1\150\125\0\1\151\64\0\1\152\122\0\1\151\71\0"+
    "\1\153\106\0\1\154\46\0\1\155\102\0\1\156\107\0"+
    "\1\155\115\0\1\157\121\0\1\160\104\0\1\160\65\0"+
    "\1\161\103\0\1\162\72\0\1\163\107\0\1\164\103\0"+
    "\1\165\75\0\1\166\77\0\1\167\110\0\1\170\115\0"+
    "\1\171\76\0\1\171\70\0\1\172\107\0\1\172\101\0"+
    "\1\173\75\0\1\174\101\0\1\175\110\0\1\176\111\0"+
    "\1\177\106\0\1\177\62\0\1\200\110\0\1\201\75\0"+
    "\1\201\23\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6298];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\2\1\1\11\3\1\3\11\1\1\11\11"+
    "\1\1\1\11\23\1\6\11\1\0\1\1\1\0\1\11"+
    "\1\1\1\0\1\11\25\0\1\11\1\0\1\1\2\0"+
    "\1\1\11\0\1\11\2\0\1\11\10\0\1\11\3\0"+
    "\1\11\2\0\1\11\10\0\2\11\4\0\1\11\1\0"+
    "\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[129];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
	private ComplexSymbolFactory csf;

	public Lexico(java.io.Reader in, ComplexSymbolFactory sf) {
		this(in);
		this.csf = sf;
	}

	private Symbol symbol(int type) {
		if (csf != null) {
			Location left  = new Location(yyline + 1, yycolumn + 1, yychar);
			Location right = new Location(yyline + 1, yycolumn + yylength(), yychar + yylength());
			return csf.newSymbol(sym.terminalNames[type], type, left, right);
		}
		return new Symbol(type);
	}

	private Symbol symbol(int type, Object value) {
		if (csf != null) {
			Location left  = new Location(yyline + 1, yycolumn + 1, yychar);
			Location right = new Location(yyline + 1, yycolumn + yylength(), yychar + yylength());
			return csf.newSymbol(sym.terminalNames[type], type, left, right, value);
		}
		return new Symbol(type, value);
	}

	BufferedWriter bw;
	File f;
	ArrayList<String> simbolsList;

	public void writeSymbolInTable(String s) throws IOException{
		if(!simbolsList.contains(s.split(",")[0])){
			bw.write(s);
			bw.newLine();
			bw.flush();
			simbolsList.add(s.split(",")[0]);
		}
	}

	public String s = "";
	final int MAX_STRING = 30;
    final int MAX_INT = 32767;


	private boolean validate_string(String textString) {
		if (textString.length() > MAX_STRING) {
			throw new RuntimeException("La longitud del lexema "+textString+" excede la esperada");
		}
		return true;
	}

    private boolean validate_int_number(String numberInt) {
		if (Integer.parseInt(numberInt) > MAX_INT || Integer.parseInt(numberInt) < - MAX_INT) {
			throw new RuntimeException("El numero entero del lexema "+numberInt+" excede el esperado");
		}
		return true;
	}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
  	try{
		String dir = System.getProperty("user.dir");
		String path = dir + "/ts.txt";
		f = new File(path);
		bw = new BufferedWriter(new FileWriter(f,false));
		simbolsList = new ArrayList<>();
	}catch (IOException e){
		e.printStackTrace();
	}
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 204) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(sym.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new Error("Caracter no permitido: '" + yytext() + "' en la linea " + (yyline+1) + ", columna " + (yycolumn+1));
            }
          case 43: break;
          case 2: 
            { return symbol(sym.AND);
            }
          case 44: break;
          case 3: 
            { 
            }
          case 45: break;
          case 4: 
            { return symbol(sym.OPMOD);
            }
          case 46: break;
          case 5: 
            { return symbol(sym.MAYOR_A);
            }
          case 47: break;
          case 6: 
            { return symbol(sym.ASIGN);
            }
          case 48: break;
          case 7: 
            { return symbol(sym.MENOR_A);
            }
          case 49: break;
          case 8: 
            { return symbol(sym.OPSUMA);
            }
          case 50: break;
          case 9: 
            { return symbol(sym.OPRESTA);
            }
          case 51: break;
          case 10: 
            { return symbol(sym.OPMULTI);
            }
          case 52: break;
          case 11: 
            { return symbol(sym.OPDIV);
            }
          case 53: break;
          case 12: 
            { return symbol(sym.PAR_A);
            }
          case 54: break;
          case 13: 
            { return symbol(sym.PAR_C);
            }
          case 55: break;
          case 14: 
            { return symbol(sym.LLAVE_A);
            }
          case 56: break;
          case 15: 
            { return symbol(sym.LLAVE_C);
            }
          case 57: break;
          case 16: 
            { return symbol(sym.CORCH_A);
            }
          case 58: break;
          case 17: 
            { return symbol(sym.CORCH_C);
            }
          case 59: break;
          case 18: 
            { return symbol(sym.COMA);
            }
          case 60: break;
          case 19: 
            { return symbol(sym.PUNTOC);
            }
          case 61: break;
          case 20: 
            { return symbol(sym.PUNTOPUNTO);
            }
          case 62: break;
          case 21: 
            { validate_int_number(yytext());
        writeSymbolInTable("_"+yytext()+", NUMENT , _ , "+yytext()+" , _ ");
        return symbol(sym.NUMENT, yytext());
            }
          case 63: break;
          case 22: 
            { return symbol(sym.OR);
            }
          case 64: break;
          case 23: 
            { return symbol(sym.NOT);
            }
          case 65: break;
          case 24: 
            { return symbol(sym.MAYOR_I);
            }
          case 66: break;
          case 25: 
            { return symbol(sym.IGUAL_A);
            }
          case 67: break;
          case 26: 
            { return symbol(sym.DISTINTO);
            }
          case 68: break;
          case 27: 
            { return symbol(sym.MENOR_I);
            }
          case 69: break;
          case 28: 
            { writeSymbolInTable("_"+yytext()+", NUMREAL , _ , "+yytext()+" , _ ");
        return symbol(sym.NUMREAL, yytext());
            }
          case 70: break;
          case 29: 
            { validate_string(yytext());
        writeSymbolInTable("_"+yytext().substring(1, yytext().length() - 1)+ ", VALSTRING , _ ,"+yytext().substring(1, yytext().length() - 1)+","+ yytext().substring(1, yytext().length() - 1).length());
        return symbol(sym.VALSTRING, yytext());
            }
          case 71: break;
          case 30: 
            { writeSymbolInTable(yytext() + ",VARIABLE,,_,_");
        return symbol(sym.VARIABLE, yytext());
            }
          case 72: break;
          case 31: 
            { return symbol(sym.IF, yytext());
            }
          case 73: break;
          case 32: 
            { return symbol(sym.INT, yytext());
            }
          case 74: break;
          case 33: 
            { return symbol(sym.END, yytext());
            }
          case 75: break;
          case 34: 
            { return symbol(sym.PUT, yytext());
            }
          case 76: break;
          case 35: 
            { return symbol(sym.ELSE, yytext());
            }
          case 77: break;
          case 36: 
            { return symbol(sym.CANT, yytext());
            }
          case 78: break;
          case 37: 
            { return symbol(sym.WHILE, yytext());
            }
          case 79: break;
          case 38: 
            { return symbol(sym.FLOAT, yytext());
            }
          case 80: break;
          case 39: 
            { return symbol(sym.STRING, yytext());
            }
          case 81: break;
          case 40: 
            { return symbol(sym.DECVAR, yytext());
            }
          case 82: break;
          case 41: 
            { return symbol(sym.PROGRAM, yytext());
            }
          case 83: break;
          case 42: 
            { return symbol(sym.ENDECVAR, yytext());
            }
          case 84: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
