
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DISTINTO = 16;
  public static final int PUT = 7;
  public static final int INT = 33;
  public static final int LLAVE_C = 26;
  public static final int LLAVE_A = 25;
  public static final int NUMENT = 40;
  public static final int ENDECVAR = 37;
  public static final int NOT = 11;
  public static final int OPSUMA = 18;
  public static final int AND = 9;
  public static final int OPMULTI = 20;
  public static final int OR = 10;
  public static final int IF = 5;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MAYOR_I = 13;
  public static final int COMA = 29;
  public static final int PAR_C = 24;
  public static final int MENOR_I = 15;
  public static final int PAR_A = 23;
  public static final int MAYOR_A = 12;
  public static final int OPDIV = 21;
  public static final int PUNTOPUNTO = 32;
  public static final int CANT = 8;
  public static final int NUMREAL = 41;
  public static final int OPRESTA = 19;
  public static final int DECVAR = 36;
  public static final int MENOR_A = 14;
  public static final int ELSE = 6;
  public static final int VARIABLE = 38;
  public static final int VALSTRING = 39;
  public static final int IGUAL_A = 17;
  public static final int WHILE = 4;
  public static final int FLOAT = 34;
  public static final int OPMOD = 22;
  public static final int PUNTOC = 31;
  public static final int ASIGN = 30;
  public static final int END = 3;
  public static final int STRING = 35;
  public static final int CORCH_C = 28;
  public static final int CORCH_A = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAM",
  "END",
  "WHILE",
  "IF",
  "ELSE",
  "PUT",
  "CANT",
  "AND",
  "OR",
  "NOT",
  "MAYOR_A",
  "MAYOR_I",
  "MENOR_A",
  "MENOR_I",
  "DISTINTO",
  "IGUAL_A",
  "OPSUMA",
  "OPRESTA",
  "OPMULTI",
  "OPDIV",
  "OPMOD",
  "PAR_A",
  "PAR_C",
  "LLAVE_A",
  "LLAVE_C",
  "CORCH_A",
  "CORCH_C",
  "COMA",
  "ASIGN",
  "PUNTOC",
  "PUNTOPUNTO",
  "INT",
  "FLOAT",
  "STRING",
  "DECVAR",
  "ENDECVAR",
  "VARIABLE",
  "VALSTRING",
  "NUMENT",
  "NUMREAL"
  };
}

